/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aggiungiFattura;

import aggiungiFattura.AggiungiFattura;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import prodotti.Prodotto;
import prodotti.Tipo;

/**
 *
 * @author Alessio
 */
public class AggiungiProdotto extends javax.swing.JFrame {

    /**
     * Creates new form AggiungiProdotto
     */
    public AggiungiProdotto(AggiungiFattura af) {
        initComponents();
        this.af=af;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrizione = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        prezzo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantità = new javax.swing.JTextField();
        servizio = new javax.swing.JRadioButton();
        hardware = new javax.swing.JRadioButton();
        aggiungi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aggiungi Prodotto");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Codice:");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        codice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Descrizione:");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        descrizione.setColumns(20);
        descrizione.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descrizione.setLineWrap(true);
        descrizione.setRows(5);
        jScrollPane2.setViewportView(descrizione);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Prezzo:");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        prezzo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Iva:");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        iva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Quantità:");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        quantità.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantità.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitàActionPerformed(evt);
            }
        });

        buttonGroup1.add(servizio);
        servizio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        servizio.setSelected(true);
        servizio.setText("Servizio");
        servizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servizioActionPerformed(evt);
            }
        });

        buttonGroup1.add(hardware);
        hardware.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        hardware.setText("Hardware");
        hardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardwareActionPerformed(evt);
            }
        });

        aggiungi.setBackground(new java.awt.Color(100, 141, 185));
        aggiungi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        aggiungi.setForeground(new java.awt.Color(254, 254, 254));
        aggiungi.setText("Aggiungi Prodotto");
        aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hardware)
                    .addComponent(servizio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(codice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantità)
                                .addGap(180, 180, 180))
                            .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggiungi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantità, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(servizio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardware)
                .addGap(35, 35, 35)
                .addComponent(aggiungi)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servizioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servizioActionPerformed

    private void hardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hardwareActionPerformed

    private void aggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiActionPerformed
        if(codice.getText().equals("") || descrizione.getText().equals("") || prezzo.getText().equals("") || iva.getText().equals("") || quantità.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            Float.parseFloat(prezzo.getText());
            Float.parseFloat(iva.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Prezzo e iva devono essere numeri positivi!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Float.parseFloat(prezzo.getText())<=0 || Float.parseFloat(iva.getText())<=0){
            JOptionPane.showMessageDialog(this,"Prezzo e iva devono essere numeri positivi!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }  
        
        try{
            Integer.parseInt(quantità.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"La quantità deve essere un intero positivo!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }       
        if(Integer.parseInt(quantità.getText())<=0){
            JOptionPane.showMessageDialog(this,"La quantità deve essere un intero positivo!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        this.dispose();
        Prodotto prodotto=null;
        if (servizio.isSelected()){
            prodotto=new Prodotto(Integer.parseInt(iva.getText()), codice.getText(), descrizione.getText(), Integer.parseInt(quantità.getText()),Float.parseFloat(prezzo.getText()),Tipo.Servizio);
        }                                                                            
        else{
            prodotto=new Prodotto(Integer.parseInt(iva.getText()), codice.getText(), descrizione.getText(), Integer.parseInt(quantità.getText()),Float.parseFloat(prezzo.getText()),Tipo.Prodotto);
        }
        af.prodottoAggiunto(prodotto);
    }//GEN-LAST:event_aggiungiActionPerformed

    private void quantitàActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitàActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitàActionPerformed

    
    private AggiungiFattura af;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiungi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codice;
    private javax.swing.JTextArea descrizione;
    private javax.swing.JRadioButton hardware;
    private javax.swing.JTextField iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField prezzo;
    private javax.swing.JTextField quantità;
    private javax.swing.JRadioButton servizio;
    // End of variables declaration//GEN-END:variables
}
