/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aggiungiFattura;


import aggiungiFattura.AggiungiFatturaController;
import aggiungiFattura.AggiungiFatturaModel;
import MVC.View;
import clienti.Cliente;
import clienti.ClientePubblico;
import fattura.Fattura;
import fattura.FatturaBusiness;
import fattura.FatturaPubblica;
import fattura.Tipologia;
import gateway.Gateway;
import gateway.GatewayConcreto;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodoPagamento.MetodoPagamento;
import metodoPagamento.Pagamento;
import prodotti.Prodotto;

/**
 *
 * @author Alessio
 */
public class AggiungiFattura extends View {

    /**
     * Creates new form GestoreFattureUI
     */
    public AggiungiFattura(AggiungiFatturaController afc, AggiungiFatturaModel afm) {
        super(afc,afm);
        aggiungiFatturaController=afc;
        aggiungiFatturaModel=afm;
        Date date = new Date();
        initComponents();
        setPagamentoModel();
        dataEmissioneFattura.setDate(date);
        dataEmissioneGara.setDate(date);
        dataScadenza.setDate(date);
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        numeroFattura = new javax.swing.JTextField();
        aggiuntaCliente = new javax.swing.JButton();
        cig = new javax.swing.JTextField();
        cup = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdotti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        aggiuntaProdotto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iban = new javax.swing.JTextField();
        pagamento = new javax.swing.JComboBox<>();
        banca = new javax.swing.JTextField();
        salvataggio = new java.awt.Checkbox();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imponibile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prezzoTotale = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelCig = new javax.swing.JLabel();
        labelCup = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aggiuntaFattura = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        dataEmissioneFattura = new com.toedter.calendar.JDateChooser();
        dataScadenza = new com.toedter.calendar.JDateChooser();
        dataEmissioneGara = new com.toedter.calendar.JDateChooser();
        labelEmissioneGara = new javax.swing.JLabel();
        fattura = new javax.swing.JRadioButton();
        notaDiCredito = new javax.swing.JRadioButton();
        labelIdentificativo = new javax.swing.JLabel();
        identificativo = new javax.swing.JTextField();
        listaClienti = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numeroFattura.setEditable(false);
        numeroFattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFatturaActionPerformed(evt);
            }
        });

        aggiuntaCliente.setText("Aggiungi cliente");
        aggiuntaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiuntaClienteActionPerformed(evt);
            }
        });

        cig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cigActionPerformed(evt);
            }
        });

        cup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupActionPerformed(evt);
            }
        });

        listaProdotti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codice", "Descrizione", "Tipo", "Quantità", "Iva", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaProdotti.setToolTipText("");
        listaProdotti.setEnabled(false);
        jScrollPane1.setViewportView(listaProdotti);
        if (listaProdotti.getColumnModel().getColumnCount() > 0) {
            listaProdotti.getColumnModel().getColumn(0).setResizable(false);
            listaProdotti.getColumnModel().getColumn(1).setResizable(false);
            listaProdotti.getColumnModel().getColumn(2).setResizable(false);
            listaProdotti.getColumnModel().getColumn(3).setResizable(false);
            listaProdotti.getColumnModel().getColumn(4).setResizable(false);
            listaProdotti.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Prodotti");

        aggiuntaProdotto.setText("Aggiungi prodotto");
        aggiuntaProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiuntaProdottoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Metodo pagamento");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        iban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanActionPerformed(evt);
            }
        });

        pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoActionPerformed(evt);
            }
        });

        banca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bancaActionPerformed(evt);
            }
        });

        salvataggio.setLabel("Salva");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Iban:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Banca:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setText("Pagamento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iban, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(banca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(salvataggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(banca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(34, 34, 34)
                .addComponent(salvataggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Totale imponibile:");

        imponibile.setEditable(false);
        imponibile.setText("0");
        imponibile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imponibileActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Iva:");

        iva.setEditable(false);
        iva.setText("0");
        iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Prezzo totale:");

        prezzoTotale.setEditable(false);
        prezzoTotale.setText("0");
        prezzoTotale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prezzoTotaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Data scadenza:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Cliente:");

        labelCig.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelCig.setText("Cig:");

        labelCup.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelCup.setText("Cup:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("N° fattura");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Data emissione fattura:");

        aggiuntaFattura.setBackground(new java.awt.Color(204, 204, 204));
        aggiuntaFattura.setText("Aggiungi");
        aggiuntaFattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiuntaFatturaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Aggiungi Fattura");

        dataEmissioneFattura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataEmissioneFatturaMouseClicked(evt);
            }
        });
        dataEmissioneFattura.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataEmissioneFatturaPropertyChange(evt);
            }
        });

        labelEmissioneGara.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelEmissioneGara.setText("Data emissione gara:");

        buttonGroup1.add(fattura);
        fattura.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        fattura.setSelected(true);
        fattura.setText("Fattura");
        fattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatturaActionPerformed(evt);
            }
        });

        buttonGroup1.add(notaDiCredito);
        notaDiCredito.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        notaDiCredito.setText("Nota di credito");
        notaDiCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaDiCreditoActionPerformed(evt);
            }
        });

        labelIdentificativo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelIdentificativo.setText("Identificativo:");

        identificativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificativoActionPerformed(evt);
            }
        });

        listaClienti.setToolTipText("");
        listaClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaClienti, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aggiuntaCliente))
                .addGap(444, 444, 444))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(notaDiCredito)
                                        .addComponent(fattura))
                                    .addGap(139, 139, 139))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(187, 187, 187)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numeroFattura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelCig)
                                                    .addComponent(labelCup))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cig, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                    .addComponent(cup)))))
                                    .addGap(26, 26, 26)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(labelEmissioneGara))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataEmissioneFattura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataEmissioneGara, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelIdentificativo)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dataScadenza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(identificativo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(prezzoTotale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(iva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(imponibile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(159, 159, 159)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(aggiuntaProdotto))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(165, 165, 165)
                                    .addComponent(aggiuntaFattura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(listaClienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aggiuntaCliente)
                .addGap(730, 730, 730))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel14)
                    .addGap(28, 28, 28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroFattura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addComponent(dataEmissioneFattura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataEmissioneGara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEmissioneGara))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCig)
                        .addComponent(fattura))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCup)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notaDiCredito)
                            .addComponent(cup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(24, 24, 24)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(aggiuntaProdotto)
                    .addGap(45, 45, 45)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imponibile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(prezzoTotale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelIdentificativo)
                        .addComponent(identificativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataScadenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addComponent(aggiuntaFattura)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupActionPerformed

    private void cigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cigActionPerformed

    private void aggiuntaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiuntaClienteActionPerformed
        AggiungiCliente ac=new AggiungiCliente(this);
        ac.setVisible(true);
    }//GEN-LAST:event_aggiuntaClienteActionPerformed

    private void numeroFatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFatturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFatturaActionPerformed

    private void listaClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientiActionPerformed
        String s=(String) listaClienti.getSelectedItem();
        String[] splits = s.split(" - ");
        int id=Integer.parseInt(splits[0]);
        for (int i=0;i<aggiungiFatturaModel.getClienti().size();i++)
            if(aggiungiFatturaModel.getClienti().get(i).getId()==id)
                aggiungiFatturaModel.setClienteSelezionato(aggiungiFatturaModel.getClienti().get(i));
        
        boolean visibilità=false;
        if(aggiungiFatturaModel.getClienteSelezionato() instanceof ClientePubblico)
            visibilità=true;            
        labelCig.setVisible(visibilità);
        labelCup.setVisible(visibilità);
        labelIdentificativo.setVisible(visibilità);
        labelEmissioneGara.setVisible(visibilità);        
        cig.setVisible(visibilità);
        cup.setVisible(visibilità);
        identificativo.setVisible(visibilità);
        dataEmissioneGara.setVisible(visibilità);    
        aggiungiFatturaController.calcoloIdNuovaFattura(dataEmissioneFattura.getDate());
    }//GEN-LAST:event_listaClientiActionPerformed

    private void bancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bancaActionPerformed

    private void pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoActionPerformed
        
    }//GEN-LAST:event_pagamentoActionPerformed

    private void ibanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanActionPerformed
        
    }//GEN-LAST:event_ibanActionPerformed

    private void aggiuntaProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiuntaProdottoActionPerformed
        AggiungiProdotto ap=new AggiungiProdotto(this);
        ap.setVisible(true);
    }//GEN-LAST:event_aggiuntaProdottoActionPerformed

    private void prezzoTotaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prezzoTotaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prezzoTotaleActionPerformed

    private void ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaActionPerformed

    private void imponibileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imponibileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imponibileActionPerformed

    private void aggiuntaFatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiuntaFatturaActionPerformed
        if(iban.getText().equals("") || banca.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(aggiungiFatturaModel.getClienteSelezionato() instanceof ClientePubblico)
            if(cig.getText().equals("") || cup.getText().equals("") || identificativo.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
                return;
            }
        if(aggiungiFatturaModel.getProdotti().isEmpty()){
            JOptionPane.showMessageDialog(this,"Devi inserire almeno un prodotto!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }    
        String ibanSelezionato=iban.getText();
        String bancaSelezionata=banca.getText();
        String pagamentoSelezionato=pagamento.getSelectedItem().toString();
        Pagamento pagamento=null;
        if(pagamentoSelezionato.equals("VF"))
            pagamento=Pagamento.vistaFattura;
        else
            pagamento=Pagamento.valueOf(pagamentoSelezionato);
        Fattura nuovaFattura=null;
        MetodoPagamento metodoPagamento= new MetodoPagamento(pagamento, bancaSelezionata, ibanSelezionato);
        if(aggiungiFatturaModel.getClienteSelezionato() instanceof ClientePubblico)
            if(fattura.isSelected())
                nuovaFattura=new FatturaPubblica(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.Fattura, metodoPagamento, dataScadenza.getDate(), cig.getText(), cup.getText(), identificativo.getText(), dataEmissioneGara.getDate());
            else
                nuovaFattura=new FatturaPubblica(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.NotaDiCredito, metodoPagamento, dataScadenza.getDate(), cig.getText(), cup.getText(), identificativo.getText(), dataEmissioneGara.getDate());
        else
            if(fattura.isSelected())
                nuovaFattura=new FatturaBusiness(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.Fattura, metodoPagamento, dataScadenza.getDate());
            else
                nuovaFattura=new FatturaBusiness(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.NotaDiCredito, metodoPagamento, dataScadenza.getDate());
        
        Gateway g=GatewayConcreto.getInstance();
        g.memorizzaFattura(nuovaFattura);
        aggiungiFatturaController.fatturaAggiunta(dataEmissioneFattura.getDate());
        cig.setText("");
        cup.setText("");
        imponibile.setText("0");
        iva.setText("0");
        prezzoTotale.setText("0");
        identificativo.setText("");
        if(salvataggio.getState())
            g.memorizzaMetodoPagamento(metodoPagamento);
        else{
            iban.setText(g.getMetodoPagamento().getIban());
            banca.setText(g.getMetodoPagamento().getBanca());
            this.pagamento.setSelectedItem(g.getMetodoPagamento().getMetodo().toString());
        }
        JOptionPane.showMessageDialog(this,"Fattura aggiunta con successo!");
    }//GEN-LAST:event_aggiuntaFatturaActionPerformed

    private void fatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatturaActionPerformed
      
    }//GEN-LAST:event_fatturaActionPerformed

    private void notaDiCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaDiCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaDiCreditoActionPerformed

    private void identificativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificativoActionPerformed

    private void dataEmissioneFatturaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataEmissioneFatturaPropertyChange
        //aggiungiFatturaController.calcoloIdNuovaFattura(dataEmissioneFattura.getDate());
    }//GEN-LAST:event_dataEmissioneFatturaPropertyChange

    private void dataEmissioneFatturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataEmissioneFatturaMouseClicked
        System.out.print("Procello");
    }//GEN-LAST:event_dataEmissioneFatturaMouseClicked

    private void setPagamentoModel(){
        Gateway g=GatewayConcreto.getInstance();
        iban.setText(g.getMetodoPagamento().getIban());
        banca.setText(g.getMetodoPagamento().getBanca());
        for (Pagamento tipoPagamento : Pagamento.values()) { 
            pagamento.addItem(tipoPagamento.toString());
        pagamento.setSelectedItem(g.getMetodoPagamento().getMetodo().etichetta);    
}
    }
    
    public void clienteAggiunto(Cliente cliente){
        aggiungiFatturaController.nuovoCliente(cliente);
    }
    
    public void prodottoAggiunto(Prodotto prodotto){
        aggiungiFatturaController.nuovoProdotto(prodotto);
    }
    
    @Override
    public void update(){
        String[] nomiEIdClienti=new String[aggiungiFatturaModel.getClienti().size()];
        for (int i=0; i<nomiEIdClienti.length; i++){
            nomiEIdClienti[i]=(Integer.toString(aggiungiFatturaModel.getClienti().get(i).getId())+" - "+aggiungiFatturaModel.getClienti().get(i).getNome());

        }    
        listaClienti.setModel(new DefaultComboBoxModel<>(nomiEIdClienti));
        listaClienti.setSelectedItem(Integer.toString(aggiungiFatturaModel.getClienteSelezionato().getId())+" - "+aggiungiFatturaModel.getClienteSelezionato().getNome());
        
        Object[][] prodotti=new Object[aggiungiFatturaModel.getProdotti().size()][listaProdotti.getColumnCount()];
        for (int i=0; i<prodotti.length; i++){
            prodotti[i][0]=aggiungiFatturaModel.getProdotti().get(i).getCodice();
            prodotti[i][1]=aggiungiFatturaModel.getProdotti().get(i).getDescrizione();
            prodotti[i][2]=aggiungiFatturaModel.getProdotti().get(i).getTipologia();
            prodotti[i][3]=aggiungiFatturaModel.getProdotti().get(i).getQuantita();
            prodotti[i][4]=aggiungiFatturaModel.getProdotti().get(i).getIva();
            prodotti[i][5]=aggiungiFatturaModel.getProdotti().get(i).getPrezzo();
        }
        String[] colonne={"Codice", "Descrizione", "Tipo", "Quantità", "Iva", "Prezzo"};
        DefaultTableModel modelloTabella=new DefaultTableModel(prodotti, colonne);
        listaProdotti.setModel(modelloTabella);
        
        numeroFattura.setText(String.valueOf(aggiungiFatturaModel.getIdNuovaFattura()));
        
        imponibile.setText(Float.toString(aggiungiFatturaModel.getImponibile()));
        iva.setText(Float.toString(aggiungiFatturaModel.getIva()));
        prezzoTotale.setText(Float.toString(aggiungiFatturaModel.getPrezzoTotale()));
        
    }


    private AggiungiFatturaController aggiungiFatturaController;
    private AggiungiFatturaModel aggiungiFatturaModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiuntaCliente;
    private javax.swing.JButton aggiuntaFattura;
    private javax.swing.JButton aggiuntaProdotto;
    private javax.swing.JTextField banca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cig;
    private javax.swing.JTextField cup;
    private com.toedter.calendar.JDateChooser dataEmissioneFattura;
    private com.toedter.calendar.JDateChooser dataEmissioneGara;
    private com.toedter.calendar.JDateChooser dataScadenza;
    private javax.swing.JRadioButton fattura;
    private javax.swing.JTextField iban;
    private javax.swing.JTextField identificativo;
    private javax.swing.JTextField imponibile;
    private javax.swing.JTextField iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCig;
    private javax.swing.JLabel labelCup;
    private javax.swing.JLabel labelEmissioneGara;
    private javax.swing.JLabel labelIdentificativo;
    private javax.swing.JComboBox<String> listaClienti;
    private javax.swing.JTable listaProdotti;
    private javax.swing.JRadioButton notaDiCredito;
    private javax.swing.JTextField numeroFattura;
    private javax.swing.JComboBox<String> pagamento;
    private javax.swing.JTextField prezzoTotale;
    private java.awt.Checkbox salvataggio;
    // End of variables declaration//GEN-END:variables
}

