/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aggiungiFattura;

import clienti.Cliente;
import clienti.ClienteBusiness;
import clienti.ClientePubblico;
import gateway.Gateway;
import gateway.GatewayConcreto;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessio
 */
public class AggiungiCliente extends javax.swing.JFrame {

    /**
     * Creates new form AggiungiCliente
     */
    public AggiungiCliente(AggiungiFattura af) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.af=af;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pubblico = new javax.swing.JRadioButton();
        privato = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        nomeAzienda = new javax.swing.JTextField();
        via = new javax.swing.JTextField();
        partitaIva = new javax.swing.JTextField();
        cap = new javax.swing.JTextField();
        codiceFiscale = new javax.swing.JTextField();
        città = new javax.swing.JTextField();
        provincia = new javax.swing.JTextField();
        nazione = new javax.swing.JTextField();
        codiceAnagrafico = new javax.swing.JTextField();
        aggiungi = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        codiceDestinatario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Aggiungi Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Nome azienda:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Via:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("P. IVA:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("CAP:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Codice fiscale:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Città:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Provincia:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Nazione:");

        buttonGroup1.add(pubblico);
        pubblico.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        pubblico.setSelected(true);
        pubblico.setText("Pubblico");
        pubblico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubblicoActionPerformed(evt);
            }
        });

        buttonGroup1.add(privato);
        privato.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        privato.setText("Privato");
        privato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privatoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Codice anagrafico (se pubblico):");

        nomeAzienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAziendaActionPerformed(evt);
            }
        });

        via.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaActionPerformed(evt);
            }
        });

        partitaIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partitaIvaActionPerformed(evt);
            }
        });

        codiceFiscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codiceFiscaleActionPerformed(evt);
            }
        });

        città.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cittàActionPerformed(evt);
            }
        });

        provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaActionPerformed(evt);
            }
        });

        nazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazioneActionPerformed(evt);
            }
        });

        codiceAnagrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codiceAnagraficoActionPerformed(evt);
            }
        });

        aggiungi.setBackground(new java.awt.Color(204, 204, 204));
        aggiungi.setText("Aggiungi");
        aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Email:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Codice destinatario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(privato)
                            .addComponent(pubblico)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(email)
                            .addComponent(nomeAzienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(via, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partitaIva, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codiceFiscale, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(città, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(provincia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazione, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codiceDestinatario, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codiceAnagrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeAzienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(via, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(partitaIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codiceFiscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(città, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(codiceDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pubblico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(privato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(codiceAnagrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(aggiungi)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pubblicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubblicoActionPerformed
        codiceAnagrafico.setEnabled(true);
    }//GEN-LAST:event_pubblicoActionPerformed

    private void privatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privatoActionPerformed
        codiceAnagrafico.setEnabled(false);
    }//GEN-LAST:event_privatoActionPerformed

    private void nomeAziendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAziendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAziendaActionPerformed

    private void viaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viaActionPerformed

    private void partitaIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partitaIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partitaIvaActionPerformed

    private void cittàActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cittàActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cittàActionPerformed

    private void nazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazioneActionPerformed

    private void codiceAnagraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codiceAnagraficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codiceAnagraficoActionPerformed

    private void aggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiActionPerformed
        if(nomeAzienda.getText().equals("") || via.getText().equals("") || partitaIva.getText().equals("") || cap.getText().equals("") || codiceFiscale.getText().equals("") || città.getText().equals("") || provincia.getText().equals("") || nazione.getText().equals("") || email.getText().equals("") || codiceDestinatario.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }    
        if(pubblico.isSelected())
            if(codiceAnagrafico.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
                return;
            }
        this.dispose();
        Gateway g=GatewayConcreto.getInstance();
        int id=g.getIdCliente();
        Cliente cliente=null;
        if (pubblico.isSelected()){
            cliente=new ClientePubblico(id, nomeAzienda.getText(), via.getText(),città.getText(), provincia.getText(), cap.getText(), partitaIva.getText(),codiceFiscale.getText(), email.getText(), codiceDestinatario.getText(),nazione.getText(), codiceAnagrafico.getText());
        }                                                                            
        else{
            cliente=new ClienteBusiness(id, nomeAzienda.getText(), via.getText(),città.getText(), provincia.getText(), cap.getText(), partitaIva.getText(),codiceFiscale.getText(), email.getText(), codiceDestinatario.getText(),nazione.getText());
        }
        af.clienteAggiunto(cliente);
            
    }//GEN-LAST:event_aggiungiActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaActionPerformed

    private void codiceFiscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codiceFiscaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codiceFiscaleActionPerformed


    private AggiungiFattura af;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiungi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cap;
    private javax.swing.JTextField città;
    private javax.swing.JTextField codiceAnagrafico;
    private javax.swing.JTextField codiceDestinatario;
    private javax.swing.JTextField codiceFiscale;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nazione;
    private javax.swing.JTextField nomeAzienda;
    private javax.swing.JTextField partitaIva;
    private javax.swing.JRadioButton privato;
    private javax.swing.JTextField provincia;
    private javax.swing.JRadioButton pubblico;
    private javax.swing.JTextField via;
    // End of variables declaration//GEN-END:variables
}
