/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aggiungiFattura;



import mvc.View;
import clienti.Cliente;
import clienti.ClientePubblico;
import fattura.Fattura;
import fattura.FatturaBusiness;
import fattura.FatturaPubblica;
import fattura.Tipologia;
import gateway.Gateway;
import gateway.GatewayConcreto;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import metodoPagamento.MetodoPagamento;
import metodoPagamento.Pagamento;
import prodotti.Prodotto;

/**
 *
 * @author Alessio
 */
public class AggiungiFattura extends View {

    /**
     * Creates new form GestoreFattureUI
     */
    public AggiungiFattura(AggiungiFatturaController afc, AggiungiFatturaModel afm) {
        super(afc,afm);
        aggiungiFatturaController=afc;
        aggiungiFatturaModel=afm;
        Date date = new Date();
        initComponents();
        setPagamentoModel(); 
        dataEmissioneFattura.setDate(date);
        aggiungiFatturaModel.setDataEmissioneFattura(date);
        dataEmissioneGara.setDate(date);
        update();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Dati = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dataEmissioneFattura = new com.toedter.calendar.JDateChooser();
        cig = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        notaDiCredito = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        aggiuntaCliente = new javax.swing.JButton();
        dataEmissioneGara = new com.toedter.calendar.JDateChooser();
        labelCup = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numeroFattura = new javax.swing.JTextField();
        fattura = new javax.swing.JRadioButton();
        labelEmissioneGara = new javax.swing.JLabel();
        listaClienti = new javax.swing.JComboBox<>();
        labelCig = new javax.swing.JLabel();
        cup = new javax.swing.JTextField();
        identificativo = new javax.swing.JTextField();
        labelIdentificativo = new javax.swing.JLabel();
        Prodotti = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdotti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        aggiuntaProdotto = new javax.swing.JButton();
        metodoPagamento = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        riepilogo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        imponibile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prezzoTotale = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataScadenza = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iban = new javax.swing.JTextField();
        pagamento = new javax.swing.JComboBox<>();
        banca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salvataggio = new java.awt.Checkbox();
        jPanel7 = new javax.swing.JPanel();
        aggiuntaFattura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dati.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setPreferredSize(new java.awt.Dimension(1242, 128));

        dataEmissioneFattura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataEmissioneFatturaMouseClicked(evt);
            }
        });
        dataEmissioneFattura.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataEmissioneFatturaPropertyChange(evt);
            }
        });

        cig.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cigActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("N° fattura");

        buttonGroup1.add(notaDiCredito);
        notaDiCredito.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        notaDiCredito.setText("Nota di credito");
        notaDiCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaDiCreditoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        aggiuntaCliente.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        aggiuntaCliente.setText("Aggiungi cliente");
        aggiuntaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiuntaClienteActionPerformed(evt);
            }
        });

        labelCup.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCup.setText("Cup:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("Data emissione fattura:");

        numeroFattura.setEditable(false);
        numeroFattura.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        numeroFattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFatturaActionPerformed(evt);
            }
        });

        buttonGroup1.add(fattura);
        fattura.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        fattura.setSelected(true);
        fattura.setText("Fattura");
        fattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatturaActionPerformed(evt);
            }
        });

        labelEmissioneGara.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelEmissioneGara.setText("Data emissione gara:");

        listaClienti.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        listaClienti.setToolTipText("");
        listaClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientiActionPerformed(evt);
            }
        });

        labelCig.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCig.setText("Cig:");

        cup.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupActionPerformed(evt);
            }
        });

        identificativo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        identificativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificativoActionPerformed(evt);
            }
        });

        labelIdentificativo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIdentificativo.setText("Identificativo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCig)
                            .addComponent(labelCup))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cig)
                            .addComponent(cup)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroFattura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aggiuntaCliente)
                    .addComponent(listaClienti, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelEmissioneGara)
                        .addGap(18, 18, 18)
                        .addComponent(dataEmissioneGara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataEmissioneFattura, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(identificativo)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(fattura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notaDiCredito)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIdentificativo)
                        .addGap(59, 59, 59))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(numeroFattura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCig)
                                    .addComponent(dataEmissioneGara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCup))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(listaClienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fattura)
                                .addComponent(notaDiCredito))
                            .addComponent(dataEmissioneFattura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aggiuntaCliente)
                            .addComponent(labelIdentificativo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEmissioneGara))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(identificativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Dati.add(jPanel4);

        Prodotti.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listaProdotti.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        listaProdotti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codice", "Descrizione", "Tipo", "Quantità", "Iva", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaProdotti.setToolTipText("");
        listaProdotti.setFocusTraversalPolicyProvider(true);
        listaProdotti.setFocusable(false);
        listaProdotti.setGridColor(new java.awt.Color(204, 204, 204));
        listaProdotti.setSelectionBackground(new java.awt.Color(100, 141, 185));
        listaProdotti.setSelectionForeground(new java.awt.Color(254, 254, 254));
        listaProdotti.setShowGrid(true);
        listaProdotti.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(listaProdotti);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prodotti");

        aggiuntaProdotto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        aggiuntaProdotto.setText("Aggiungi prodotto");
        aggiuntaProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiuntaProdottoActionPerformed(evt);
            }
        });
        jPanel5.add(aggiuntaProdotto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1242, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Prodotti.add(jPanel3);

        metodoPagamento.setBackground(getBackground());
        metodoPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setPreferredSize(new java.awt.Dimension(1242, 634));
        jPanel6.setLayout(new java.awt.BorderLayout());

        riepilogo.setMaximumSize(new java.awt.Dimension(32767, 212766));
        riepilogo.setMinimumSize(new java.awt.Dimension(0, 0));
        riepilogo.setPreferredSize(new java.awt.Dimension(308, 116));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Totale imponibile:");

        imponibile.setEditable(false);
        imponibile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imponibile.setText("0");
        imponibile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imponibileActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Iva:");

        iva.setEditable(false);
        iva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iva.setText("0");
        iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Prezzo totale:");

        prezzoTotale.setEditable(false);
        prezzoTotale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prezzoTotale.setText("0");
        prezzoTotale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prezzoTotaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Data scadenza:");

        dataScadenza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataScadenza.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataScadenzaPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Riepilogo");

        javax.swing.GroupLayout riepilogoLayout = new javax.swing.GroupLayout(riepilogo);
        riepilogo.setLayout(riepilogoLayout);
        riepilogoLayout.setHorizontalGroup(
            riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riepilogoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(riepilogoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imponibile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prezzoTotale, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataScadenza, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(123, Short.MAX_VALUE))))
        );
        riepilogoLayout.setVerticalGroup(
            riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riepilogoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataScadenza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(imponibile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(prezzoTotale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        jPanel6.add(riepilogo, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(611, 134));

        iban.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanActionPerformed(evt);
            }
        });

        pagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoActionPerformed(evt);
            }
        });

        banca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        banca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bancaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Iban:");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setText("Banca:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setText("Pagamento:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Metodo pagamento");

        salvataggio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        salvataggio.setLabel("Salva");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(591, 591, 591)
                .addComponent(salvataggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(iban, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(banca, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(banca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salvataggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        aggiuntaFattura.setBackground(new java.awt.Color(100, 141, 185));
        aggiuntaFattura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        aggiuntaFattura.setForeground(new java.awt.Color(255, 255, 255));
        aggiuntaFattura.setText("Aggiungi Fattura");
        aggiuntaFattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiuntaFatturaActionPerformed(evt);
            }
        });
        jPanel7.add(aggiuntaFattura);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout metodoPagamentoLayout = new javax.swing.GroupLayout(metodoPagamento);
        metodoPagamento.setLayout(metodoPagamentoLayout);
        metodoPagamentoLayout.setHorizontalGroup(
            metodoPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodoPagamentoLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        metodoPagamentoLayout.setVerticalGroup(
            metodoPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodoPagamentoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Prodotti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1624, Short.MAX_VALUE)
                    .addComponent(Dati, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(metodoPagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Dati, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Prodotti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(metodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupActionPerformed

    private void cigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cigActionPerformed

    private void aggiuntaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiuntaClienteActionPerformed
        AggiungiCliente ac=new AggiungiCliente(this);
        ac.setVisible(true);
    }//GEN-LAST:event_aggiuntaClienteActionPerformed

    private void numeroFatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFatturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFatturaActionPerformed

    private void listaClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientiActionPerformed
         String s=(String) listaClienti.getSelectedItem();
        String[] splits = s.split(" - ");
        int id=Integer.parseInt(splits[0]);
        for (int i=0;i<aggiungiFatturaModel.getClienti().size();i++)
            if(aggiungiFatturaModel.getClienti().get(i).getId()==id)
                aggiungiFatturaModel.setClienteSelezionato(aggiungiFatturaModel.getClienti().get(i));
        
        boolean visibilità=false;
        if(aggiungiFatturaModel.getClienteSelezionato() instanceof ClientePubblico)
            visibilità=true;            
        labelCig.setVisible(visibilità);
        labelCup.setVisible(visibilità);
        labelIdentificativo.setVisible(visibilità);
        labelEmissioneGara.setVisible(visibilità);        
        cig.setVisible(visibilità);
        cup.setVisible(visibilità);
        identificativo.setVisible(visibilità);
        dataEmissioneGara.setVisible(visibilità);    
        aggiungiFatturaController.calcoloIdNuovaFattura();
    }//GEN-LAST:event_listaClientiActionPerformed

    private void bancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bancaActionPerformed

    private void pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoActionPerformed
          String metodoSelezionato = (String) pagamento.getSelectedItem();
        if (metodoSelezionato.equals("VF"))
            dataScadenza.setEnabled(true);
        else{
            dataScadenza.setEnabled(false);
            
            aggiungiFatturaController.modificaScadenza(metodoSelezionato);
        }    
    }//GEN-LAST:event_pagamentoActionPerformed

    private void ibanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanActionPerformed
        
    }//GEN-LAST:event_ibanActionPerformed

    private void aggiuntaProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiuntaProdottoActionPerformed
        AggiungiProdotto ap=new AggiungiProdotto(this);
        ap.setVisible(true);
    }//GEN-LAST:event_aggiuntaProdottoActionPerformed

    private void prezzoTotaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prezzoTotaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prezzoTotaleActionPerformed

    private void ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaActionPerformed

    private void imponibileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imponibileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imponibileActionPerformed

    private void aggiuntaFatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiuntaFatturaActionPerformed
       if(iban.getText().equals("") || banca.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(aggiungiFatturaModel.getClienteSelezionato() instanceof ClientePubblico)
            if(cig.getText().equals("") || cup.getText().equals("") || identificativo.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Tutti i campi devono essere compilati!","Errore",JOptionPane.ERROR_MESSAGE);
                return;
            }
        if(aggiungiFatturaModel.getProdotti().isEmpty()){
            JOptionPane.showMessageDialog(this,"Devi inserire almeno un prodotto!","Errore",JOptionPane.ERROR_MESSAGE);
            return;
        }    
        String ibanSelezionato=iban.getText();
        String bancaSelezionata=banca.getText();
        String pagamentoSelezionato=pagamento.getSelectedItem().toString();
        Pagamento pagamento=null;
        if(pagamentoSelezionato.equals("VF"))
            pagamento=Pagamento.vistaFattura;
        else
            pagamento=Pagamento.valueOf(pagamentoSelezionato);
        Fattura nuovaFattura=null;
        MetodoPagamento metodoPagamento= new MetodoPagamento(pagamento, bancaSelezionata, ibanSelezionato);
        if(aggiungiFatturaModel.getClienteSelezionato() instanceof ClientePubblico)
            if(fattura.isSelected())
                nuovaFattura=new FatturaPubblica(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.Fattura, metodoPagamento, dataScadenza.getDate(), cig.getText(), cup.getText(), identificativo.getText(), dataEmissioneGara.getDate());
            else
                nuovaFattura=new FatturaPubblica(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.NotaDiCredito, metodoPagamento, dataScadenza.getDate(), cig.getText(), cup.getText(), identificativo.getText(), dataEmissioneGara.getDate());
        else
            if(fattura.isSelected())
                nuovaFattura=new FatturaBusiness(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.Fattura, metodoPagamento, dataScadenza.getDate());
            else
                nuovaFattura=new FatturaBusiness(aggiungiFatturaModel.getClienteSelezionato(), Integer.parseInt(numeroFattura.getText()), dataEmissioneFattura.getDate(), aggiungiFatturaModel.getProdotti(), Tipologia.NotaDiCredito, metodoPagamento, dataScadenza.getDate());
        
        aggiungiFatturaController.fatturaAggiunta(dataEmissioneFattura.getDate(),nuovaFattura);
        cig.setText("");
        cup.setText("");
        imponibile.setText("0");
        iva.setText("0");
        prezzoTotale.setText("0");
        identificativo.setText("");
        Gateway g=GatewayConcreto.getInstance();
        if(salvataggio.getState())
            g.memorizzaMetodoPagamento(metodoPagamento);
        else{
            iban.setText(g.getMetodoPagamento().getIban());
            banca.setText(g.getMetodoPagamento().getBanca());
            this.pagamento.setSelectedItem(g.getMetodoPagamento().getMetodo().toString());
        }
        JOptionPane.showMessageDialog(this,"Fattura aggiunta con successo!");
    }//GEN-LAST:event_aggiuntaFatturaActionPerformed

    private void fatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatturaActionPerformed
      
    }//GEN-LAST:event_fatturaActionPerformed

    private void notaDiCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaDiCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaDiCreditoActionPerformed

    private void identificativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificativoActionPerformed

    private void dataEmissioneFatturaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataEmissioneFatturaPropertyChange

        if(dataEmissioneFattura.getDate()!=null){
            String pagamentoSelezionato=(String) pagamento.getSelectedItem();
            if(dataEmissioneFattura.getDate()!=aggiungiFatturaModel.getDataEmissioneFattura()){ 
                aggiungiFatturaModel.setDataEmissioneFattura(dataEmissioneFattura.getDate());
                aggiungiFatturaController.calcoloIdNuovaFattura();
                if(!pagamentoSelezionato.equals("VF"))
                    aggiungiFatturaController.modificaScadenza(pagamentoSelezionato);
            }            
        }    
    }//GEN-LAST:event_dataEmissioneFatturaPropertyChange

    private void dataEmissioneFatturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataEmissioneFatturaMouseClicked
        System.out.print("Procello");
    }//GEN-LAST:event_dataEmissioneFatturaMouseClicked

    private void dataScadenzaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataScadenzaPropertyChange
      if(dataScadenza.getDate()!=null)   
            if(((String) pagamento.getSelectedItem()).equals("VF"))
                aggiungiFatturaModel.setDataScadenza(dataScadenza.getDate());
    }//GEN-LAST:event_dataScadenzaPropertyChange

    private void setPagamentoModel(){
        Gateway g=GatewayConcreto.getInstance();
        iban.setText(g.getMetodoPagamento().getIban());
        banca.setText(g.getMetodoPagamento().getBanca());
        for (Pagamento tipoPagamento : Pagamento.values()) { 
            pagamento.addItem(tipoPagamento.toString());
        pagamento.setSelectedItem(g.getMetodoPagamento().getMetodo().etichetta);    
}
    }
    
    public void clienteAggiunto(Cliente cliente){
        aggiungiFatturaController.nuovoCliente(cliente);
    }
    
    public void prodottoAggiunto(Prodotto prodotto){
        aggiungiFatturaController.nuovoProdotto(prodotto);
    }
    
    @Override
    public void update(){
          String[] nomiEIdClienti=new String[aggiungiFatturaModel.getClienti().size()];
        for (int i=0; i<nomiEIdClienti.length; i++){
            nomiEIdClienti[i]=(Integer.toString(aggiungiFatturaModel.getClienti().get(i).getId())+" - "+aggiungiFatturaModel.getClienti().get(i).getNome());

        }    
        listaClienti.setModel(new DefaultComboBoxModel<>(nomiEIdClienti));
        if(nomiEIdClienti.length>0) //modificato
            listaClienti.setSelectedItem(Integer.toString(aggiungiFatturaModel.getClienteSelezionato().getId())+" - "+aggiungiFatturaModel.getClienteSelezionato().getNome());
        
        Object[][] prodotti=new Object[aggiungiFatturaModel.getProdotti().size()][listaProdotti.getColumnCount()];
        for (int i=0; i<prodotti.length; i++){
            prodotti[i][0]=aggiungiFatturaModel.getProdotti().get(i).getCodice();
            prodotti[i][1]=aggiungiFatturaModel.getProdotti().get(i).getDescrizione();
            prodotti[i][2]=aggiungiFatturaModel.getProdotti().get(i).getTipologia();
            prodotti[i][3]=aggiungiFatturaModel.getProdotti().get(i).getQuantita();
            prodotti[i][4]=aggiungiFatturaModel.getProdotti().get(i).getIva();
            prodotti[i][5]=aggiungiFatturaModel.getProdotti().get(i).getPrezzo();
        }
        String[] colonne={"Codice", "Descrizione", "Tipo", "Quantità", "Iva", "Prezzo"};
        DefaultTableModel modelloTabella=new DefaultTableModel(prodotti, colonne);
        listaProdotti.setModel(modelloTabella);
        
        numeroFattura.setText(String.valueOf(aggiungiFatturaModel.getIdNuovaFattura()));
        
        imponibile.setText(Float.toString(aggiungiFatturaModel.getImponibile()));
        iva.setText(Float.toString(aggiungiFatturaModel.getIva()));
        prezzoTotale.setText(Float.toString(aggiungiFatturaModel.getPrezzoTotale()));
        dataScadenza.setDate(aggiungiFatturaModel.getDataScadenza());
        centraColonne();
        
    }
    private void centraColonne() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        for (int columnIndex = 0; columnIndex < listaProdotti.getColumnCount(); columnIndex++)
        {
            listaProdotti.getColumnModel().getColumn(columnIndex).setCellRenderer(centerRenderer);
        }
    }


    private AggiungiFatturaController aggiungiFatturaController;
    private AggiungiFatturaModel aggiungiFatturaModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dati;
    private javax.swing.JPanel Prodotti;
    private javax.swing.JButton aggiuntaCliente;
    private javax.swing.JButton aggiuntaFattura;
    private javax.swing.JButton aggiuntaProdotto;
    private javax.swing.JTextField banca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cig;
    private javax.swing.JTextField cup;
    private com.toedter.calendar.JDateChooser dataEmissioneFattura;
    private com.toedter.calendar.JDateChooser dataEmissioneGara;
    private com.toedter.calendar.JDateChooser dataScadenza;
    private javax.swing.JRadioButton fattura;
    private javax.swing.JTextField iban;
    private javax.swing.JTextField identificativo;
    private javax.swing.JTextField imponibile;
    private javax.swing.JTextField iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCig;
    private javax.swing.JLabel labelCup;
    private javax.swing.JLabel labelEmissioneGara;
    private javax.swing.JLabel labelIdentificativo;
    private javax.swing.JComboBox<String> listaClienti;
    private javax.swing.JTable listaProdotti;
    private javax.swing.JPanel metodoPagamento;
    private javax.swing.JRadioButton notaDiCredito;
    private javax.swing.JTextField numeroFattura;
    private javax.swing.JComboBox<String> pagamento;
    private javax.swing.JTextField prezzoTotale;
    private javax.swing.JPanel riepilogo;
    private java.awt.Checkbox salvataggio;
    // End of variables declaration//GEN-END:variables
}

