/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FiltraFatture;

import clienti.Cliente;
import fattura.Fattura;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import metodoPagamento.MetodoPagamento;
import prodotti.Prodotto;

/**
 *
 * @author Default
 */
public class VisualizzaFattura extends javax.swing.JFrame {
    final Fattura fattura;
    /**
     * Creates new form VisualizzaFattura
     */
    public VisualizzaFattura(Fattura fattura) {
        initComponents();
      //  this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
        this.fattura=fattura;
        aggiungiProdottiTabella();
        riempiDati();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        Intestazione = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        riepilogo = new javax.swing.JPanel();
        specifiche = new javax.swing.JPanel();
        numeroFatturaView = new javax.swing.JTextField();
        metodoView = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tipologiaView = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pagatoCheck = new javax.swing.JCheckBox();
        bancaView = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dataScadenzaView = new javax.swing.JTextField();
        ibanView = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dataEmissioneView = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cliente = new javax.swing.JPanel();
        nomeView = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        viaView = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cittaView = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        provinciaView = new javax.swing.JTextField();
        capView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nazioneView = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        partitaIvaView = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailView = new javax.swing.JTextField();
        prodotti = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodottiTable = new javax.swing.JTable();
        totaleView = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        imponibileView = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ivaTotView = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel3.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jPanel3AncestorResized(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Upload s.n.c\nvia Donizzetti,17\n50019 Sesto Fiorentino (FI)\ntel:055-442006\ncell:348-5826035");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(240, 240, 240));
        jScrollPane3.setViewportView(jTextArea1);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout IntestazioneLayout = new javax.swing.GroupLayout(Intestazione);
        Intestazione.setLayout(IntestazioneLayout);
        IntestazioneLayout.setHorizontalGroup(
            IntestazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntestazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 498, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IntestazioneLayout.setVerticalGroup(
            IntestazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntestazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntestazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        numeroFatturaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        numeroFatturaView.setActionCommand("<Not Set>");
        numeroFatturaView.setBorder(null);
        numeroFatturaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        numeroFatturaView.setEnabled(false);
        numeroFatturaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFatturaViewActionPerformed(evt);
            }
        });

        metodoView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        metodoView.setActionCommand("<Not Set>");
        metodoView.setBorder(null);
        metodoView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        metodoView.setEnabled(false);
        metodoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoViewActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel17.setText("Metodo:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setText("Banca:");

        tipologiaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tipologiaView.setActionCommand("<Not Set>");
        tipologiaView.setBorder(null);
        tipologiaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tipologiaView.setEnabled(false);
        tipologiaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipologiaViewActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setText("Iban:");

        pagatoCheck.setEnabled(false);
        pagatoCheck.setFocusable(false);
        pagatoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagatoCheckActionPerformed(evt);
            }
        });

        bancaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        bancaView.setActionCommand("<Not Set>");
        bancaView.setBorder(null);
        bancaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bancaView.setEnabled(false);
        bancaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bancaViewActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setText("Pagato");

        dataScadenzaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dataScadenzaView.setActionCommand("<Not Set>");
        dataScadenzaView.setBorder(null);
        dataScadenzaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dataScadenzaView.setEnabled(false);
        dataScadenzaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataScadenzaViewActionPerformed(evt);
            }
        });

        ibanView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ibanView.setActionCommand("<Not Set>");
        ibanView.setBorder(null);
        ibanView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ibanView.setEnabled(false);
        ibanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanViewActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Tipologia:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setText("Data Scadenza:");

        dataEmissioneView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dataEmissioneView.setActionCommand("<Not Set>");
        dataEmissioneView.setBorder(null);
        dataEmissioneView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dataEmissioneView.setEnabled(false);
        dataEmissioneView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataEmissioneViewActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Data Emissione:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Numero Fattura:");

        javax.swing.GroupLayout specificheLayout = new javax.swing.GroupLayout(specifiche);
        specifiche.setLayout(specificheLayout);
        specificheLayout.setHorizontalGroup(
            specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specificheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(pagatoCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(metodoView))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataScadenzaView))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ibanView, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bancaView, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipologiaView))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataEmissioneView))
                    .addGroup(specificheLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroFatturaView)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        specificheLayout.setVerticalGroup(
            specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specificheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tipologiaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroFatturaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dataEmissioneView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagatoCheck)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dataScadenzaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ibanView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(bancaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(specificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(metodoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pagatoCheck.getAccessibleContext().setAccessibleName("pagatoCeck");

        cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        nomeView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nomeView.setActionCommand("<Not Set>");
        nomeView.setBorder(null);
        nomeView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nomeView.setEnabled(false);
        nomeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeViewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Nome:");

        viaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        viaView.setActionCommand("<Not Set>");
        viaView.setBorder(null);
        viaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        viaView.setEnabled(false);
        viaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaViewActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Via:");

        cittaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cittaView.setActionCommand("<Not Set>");
        cittaView.setBorder(null);
        cittaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cittaView.setEnabled(false);
        cittaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cittaViewActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Città:");

        provinciaView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        provinciaView.setActionCommand("<Not Set>");
        provinciaView.setBorder(null);
        provinciaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        provinciaView.setEnabled(false);
        provinciaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaViewActionPerformed(evt);
            }
        });

        capView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        capView.setActionCommand("<Not Set>");
        capView.setBorder(null);
        capView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        capView.setEnabled(false);
        capView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capViewActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Cap:");

        nazioneView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nazioneView.setActionCommand("<Not Set>");
        nazioneView.setBorder(null);
        nazioneView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nazioneView.setEnabled(false);
        nazioneView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazioneViewActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Partita Iva:");

        partitaIvaView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        partitaIvaView.setActionCommand("<Not Set>");
        partitaIvaView.setBorder(null);
        partitaIvaView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        partitaIvaView.setEnabled(false);
        partitaIvaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partitaIvaViewActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Email:");

        emailView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emailView.setActionCommand("<Not Set>");
        emailView.setBorder(null);
        emailView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        emailView.setEnabled(false);
        emailView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(clienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(capView))
                            .addGroup(clienteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cittaView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(provinciaView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nazioneView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeView))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viaView))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(partitaIvaView, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(emailView))))
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(viaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cittaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinciaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazioneView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(capView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(partitaIvaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        prodottiTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        prodottiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codice", "Descrizione", "Tipo", "Prezzo", "iva", "Quantità", "Totale"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodottiTable.setToolTipText("");
        prodottiTable.setAutoscrolls(false);
        prodottiTable.setFillsViewportHeight(true);
        prodottiTable.setFocusable(false);
        prodottiTable.setGridColor(new java.awt.Color(228, 230, 235));
        prodottiTable.setSelectionBackground(new java.awt.Color(228, 230, 235));
        prodottiTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        prodottiTable.setShowGrid(true);
        prodottiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodottiTableMouseClicked(evt);
            }
        });
        prodottiTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prodottiTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(prodottiTable);
        if (prodottiTable.getColumnModel().getColumnCount() > 0) {
            prodottiTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            prodottiTable.getColumnModel().getColumn(1).setPreferredWidth(300);
            prodottiTable.getColumnModel().getColumn(2).setPreferredWidth(25);
            prodottiTable.getColumnModel().getColumn(3).setPreferredWidth(30);
            prodottiTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            prodottiTable.getColumnModel().getColumn(5).setPreferredWidth(20);
            prodottiTable.getColumnModel().getColumn(6).setPreferredWidth(35);
        }

        totaleView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        totaleView.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totaleView.setActionCommand("<Not Set>");
        totaleView.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        totaleView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totaleView.setEnabled(false);
        totaleView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaleViewActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Totale:");

        imponibileView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        imponibileView.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        imponibileView.setActionCommand("<Not Set>");
        imponibileView.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        imponibileView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        imponibileView.setEnabled(false);
        imponibileView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imponibileViewActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Imponibile:");

        ivaTotView.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ivaTotView.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ivaTotView.setActionCommand("<Not Set>");
        ivaTotView.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ivaTotView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ivaTotView.setEnabled(false);
        ivaTotView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaTotViewActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Iva totale:");

        javax.swing.GroupLayout prodottiLayout = new javax.swing.GroupLayout(prodotti);
        prodotti.setLayout(prodottiLayout);
        prodottiLayout.setHorizontalGroup(
            prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodottiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(prodottiLayout.createSequentialGroup()
                        .addGroup(prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imponibileView)
                            .addComponent(totaleView)
                            .addComponent(ivaTotView))))
                .addContainerGap())
        );
        prodottiLayout.setVerticalGroup(
            prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodottiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prodottiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ivaTotView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(imponibileView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(prodottiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prodottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaleView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        javax.swing.GroupLayout riepilogoLayout = new javax.swing.GroupLayout(riepilogo);
        riepilogo.setLayout(riepilogoLayout);
        riepilogoLayout.setHorizontalGroup(
            riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riepilogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prodotti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(riepilogoLayout.createSequentialGroup()
                        .addComponent(specifiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        riepilogoLayout.setVerticalGroup(
            riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riepilogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riepilogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specifiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodotti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riepilogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Intestazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Intestazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(riepilogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel3AncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3AncestorResized

    private void metodoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoViewActionPerformed

    private void bancaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bancaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bancaViewActionPerformed

    private void ibanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibanViewActionPerformed

    private void pagatoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagatoCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagatoCheckActionPerformed

    private void dataScadenzaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataScadenzaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataScadenzaViewActionPerformed

    private void tipologiaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipologiaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipologiaViewActionPerformed

    private void totaleViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaleViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaleViewActionPerformed

    private void ivaTotViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaTotViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaTotViewActionPerformed

    private void imponibileViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imponibileViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imponibileViewActionPerformed

    private void dataEmissioneViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEmissioneViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEmissioneViewActionPerformed

    private void numeroFatturaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFatturaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFatturaViewActionPerformed

    private void emailViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailViewActionPerformed

    private void partitaIvaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partitaIvaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partitaIvaViewActionPerformed

    private void nazioneViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazioneViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazioneViewActionPerformed

    private void capViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capViewActionPerformed

    private void provinciaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaViewActionPerformed

    private void cittaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cittaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cittaViewActionPerformed

    private void viaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viaViewActionPerformed

    private void nomeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeViewActionPerformed

    private void prodottiTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodottiTableKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_prodottiTableKeyPressed

    private void prodottiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodottiTableMouseClicked
        
    }//GEN-LAST:event_prodottiTableMouseClicked

   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Intestazione;
    private javax.swing.JTextField bancaView;
    private javax.swing.JTextField capView;
    private javax.swing.JTextField cittaView;
    private javax.swing.JPanel cliente;
    private javax.swing.JTextField dataEmissioneView;
    private javax.swing.JTextField dataScadenzaView;
    private javax.swing.JTextField emailView;
    private javax.swing.JTextField ibanView;
    private javax.swing.JTextField imponibileView;
    private javax.swing.JTextField ivaTotView;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField metodoView;
    private javax.swing.JTextField nazioneView;
    private javax.swing.JTextField nomeView;
    private javax.swing.JTextField numeroFatturaView;
    private javax.swing.JCheckBox pagatoCheck;
    private javax.swing.JTextField partitaIvaView;
    private javax.swing.JPanel prodotti;
    private javax.swing.JTable prodottiTable;
    private javax.swing.JTextField provinciaView;
    private javax.swing.JPanel riepilogo;
    private javax.swing.JPanel specifiche;
    private javax.swing.JTextField tipologiaView;
    private javax.swing.JTextField totaleView;
    private javax.swing.JTextField viaView;
    // End of variables declaration//GEN-END:variables

    private void aggiungiProdottiTabella() {
        DefaultTableModel modelTable = (DefaultTableModel) prodottiTable.getModel();
        
        for(int i=0;i<fattura.getArticoli().size();i++){
            Prodotto p=fattura.getArticoli().get(i);
            float totale=p.getQuantita()*p.getPrezzo();
            modelTable.addRow(new Object[]{p.getCodice(),p.getDescrizione(),p.getTipologia().toString(),Float.toString(p.getPrezzo())+"€",Integer.toString(p.getIva()),Integer.toString(p.getQuantita()),Float.toString(totale)+"€"});
        }
        centraColonne(modelTable);
        
    }

private void centraColonne(DefaultTableModel modelTable) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        for (int columnIndex = 0; columnIndex < prodottiTable.getColumnCount(); columnIndex++)
        {
            prodottiTable.getColumnModel().getColumn(columnIndex).setCellRenderer(centerRenderer);
        }
    }

    private void riempiDati() {
    MetodoPagamento mp= fattura.getMetodoPagamento();
    Cliente c=fattura.getCliente();        
    bancaView.setText(mp.getBanca());
    capView.setText(c.getCap());
    cittaView.setText(c.getCitta());
   
    dataEmissioneView.setText(dateToString(fattura.getDataEmissione()));
    dataScadenzaView.setText(dateToString(fattura.getDataScadenza()));
    emailView.setText(c.getEmail());
    ibanView.setText(mp.getIban());
    imponibileView.setText(Float.toString(fattura.getImponibile())+"€");
    ivaTotView.setText(Float.toString(fattura.getIvaTot())+"€");
    metodoView.setText(mp.getMetodo().toString());
     nazioneView.setText(c.getNazione());
    nomeView.setText(c.getNome());
     numeroFatturaView.setText(Integer.toString(fattura.getNumeroFattura()));
     pagatoCheck.setSelected(fattura.getPagato());
     partitaIvaView.setText(c.getPartitaIva());
     provinciaView.setText(c.getProvincia());
     tipologiaView.setText(fattura.getTipologia().toString());
     totaleView.setText(Float.toString(fattura.getTotale())+"€");
     viaView.setText(c.getVia());
    }
     protected String dateToString(Date d){
        SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy");
        return sd.format(d);
    }
}